### ISSUE TITLE
include the global version in each response

### ISSUE THREAD

**Issue by ghost** [zk1931/pulsefs#45]
include the global version in each response. client can then send the global version in the request header to make sure it doesn't go back in time when failing over to another server. this is similar to how zookeeper client includes last seen zxid in the session handshake. we can call it 'global-version' or something.

**Comment by EasonLiao** [comment]
This idea is great, the only problem is when I should put the "global version" header. This is more like a design problem, I was thinking to add a filter to servlet so for every response we can add header to it, but the problem is the filer gets invoked only when request comes, not reply sends out. If you have better ideas please let me know.

**Comment by EasonLiao** [comment]
solved in #63
